name: Nature is happy
favicon: null
layout_spectrum: 0.98734
typography_spectrum: 0.07407
title: Nature is happy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#212428'
    - '#cf6800'
    - '#ffb543'
    - '#92948e'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
