name: Nature is happy
favicon: null
layout_spectrum: 0.6808439551386982
typography_spectrum: 0.06298882118426263
title: Nature is happy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.17470700480043888
  lightness: 0.27185574267059565
  saturation: 0.5744639954064041
  rhythmicContrast: 0.23620384908281267
purpose: []
