name: Nature is happy
favicon: null
layout_spectrum: 0.23306
typography_spectrum: 0.07407
title: Reconnecting to nature
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#212428'
    - '#cf6800'
    - '#ffb543'
    - '#92948e'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
